export const BUSINESS = {
  name: "Taller Ancestral",
  tagline: "Manufactura Artesanal de Alto Diseño",
  description: "Fusionamos 6 técnicas ancestrales en piezas únicas para tu espacio",
  city: "Ovalle",
  region: "Región de Coquimbo",
  country: "Chile",
  whatsapp: "+56912345678",
  email: "contacto@tallerancentral.cl",
  instagram: "@tallerancentral",
  facebook: "tallerancentral",
}

export const TECHNIQUES = [
  { id: "carpinteria", label: "Carpintería en Madera", icon: "🪵" },
  { id: "soldadura", label: "Soldadura y Herrería", icon: "🔥" },
  { id: "resina", label: "Resina Epóxica Certificada", icon: "✨" },
  { id: "vitral", label: "Vitrales Artísticos", icon: "🎨" },
  { id: "ceramica", label: "Cerámica Profesional", icon: "🏺" },
  { id: "construccion", label: "Construcción Antisísmica", icon: "🏗️" },
]

export const CATEGORIES = [
  {
    id: "mobiliario",
    name: "Mobiliario Premium",
    slug: "mobiliario-premium",
    description: "Mesas, escritorios y muebles que combinan madera nativa, resina epóxica y estructuras metálicas hechas a mano.",
    icon: "🛋️",
  },
  {
    id: "iluminacion",
    name: "Iluminación Artística",
    slug: "iluminacion-artistica",
    description: "Lámparas de vitral con estructuras de metal forjado, bases de cerámica artesanal y detalles en resina.",
    icon: "💡",
  },
  {
    id: "arquitectonico",
    name: "Elementos Arquitectónicos",
    slug: "elementos-arquitectonicos",
    description: "Puertas con vitrales, mamparas decorativas, ventanas artísticas y estructuras antisísmicas.",
    icon: "🏛️",
  },
  {
    id: "decoracion",
    name: "Decoración",
    slug: "decoracion",
    description: "Objetos de rotación rápida: tablas, bandejas, cuadros, maceteros y espejos artesanales.",
    icon: "🎭",
  },
  {
    id: "outdoor",
    name: "Outdoor & Parrillas",
    slug: "outdoor-parrillas",
    description: "Parrillas custom, fogoneros artísticos y muebles de exterior en metal y madera.",
    icon: "🔥",
  },
  {
    id: "elqui",
    name: "Edición Valle del Elqui",
    slug: "edicion-valle-elqui",
    description: "Piezas exclusivas con madera local, cerámica con pigmentos naturales y artesanía nativa premium.",
    icon: "🌄",
  },
]

export const PRODUCT_SEGMENTS = [
  { value: "particular", label: "Particular" },
  { value: "arquitecto", label: "Arquitecto" },
  { value: "disenador", label: "Diseñador" },
  { value: "empresa", label: "Empresa" },
  { value: "hotel_restaurante", label: "Hotel / Restaurante" },
]

export const CUSTOMER_SEGMENTS = [
  { value: "vip", label: "VIP" },
  { value: "recurrente", label: "Recurrente" },
  { value: "nuevo", label: "Nuevo" },
  { value: "inactivo", label: "Inactivo" },
]

export const EXPENSE_CATEGORIES = [
  "Arriendo taller",
  "Electricidad",
  "Agua",
  "Internet",
  "Materiales - Madera",
  "Materiales - Metales",
  "Materiales - Resina",
  "Materiales - Vidrio",
  "Materiales - Cerámica",
  "Herramientas",
  "Transporte / Despacho",
  "Marketing",
  "Contador",
  "Seguros",
  "Varios",
]

export const INVENTORY_CATEGORIES = [
  "Maderas",
  "Metales",
  "Resina Epóxica",
  "Vidrios",
  "Cerámica",
  "Herrajes y Accesorios",
  "Consumibles",
  "Pinturas y Acabados",
]

export const PAYMENT_METHODS = [
  { value: "efectivo", label: "Efectivo" },
  { value: "transferencia", label: "Transferencia Bancaria" },
  { value: "debito", label: "Tarjeta Débito" },
  { value: "credito", label: "Tarjeta Crédito" },
  { value: "mercado_pago", label: "Mercado Pago" },
]

export const IVA_RATE = 0.19

export const SAMPLE_PRODUCTS = [
  {
    id: "1",
    name: "Mesa de Río Grande",
    slug: "mesa-de-rio-grande",
    sku: "MOB-001",
    category_id: "mobiliario",
    short_description: "Mesa de río con madera nativa, resina epóxica azul y estructura metálica artesanal",
    long_description: "Obra maestra de nuestra manufactura. Cada mesa de río es única e irrepetible. La madera nativa del Valle del Elqui se combina con resina epóxica transparente con pigmentos azul océano, sobre una robusta estructura de fierro cuadrado con acabado negro mate.",
    techniques: ["carpinteria", "resina", "soldadura"],
    images: ["/images/mesa-rio-1.jpg", "/images/mesa-rio-2.jpg"],
    base_price: 850000,
    material_cost: 280000,
    production_days: 21,
    profit_margin: 67,
    is_visible: true,
    is_featured: true,
    dimensions: "200cm x 90cm x 75cm",
    materials: "Madera nativa, resina epóxica azul, fierro cuadrado 20x20",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Lámpara Vitral Industrial",
    slug: "lampara-vitral-industrial",
    sku: "ILU-001",
    category_id: "iluminacion",
    short_description: "Lámpara colgante de vitral tiffany con estructura de fierro negro",
    long_description: "Luminaria artística que combina la técnica centenaria del vitral Tiffany con una estructura metálica forjada a mano. Los vidrios de colores filtran la luz creando atmósferas únicas.",
    techniques: ["vitral", "soldadura"],
    images: ["/images/lampara-vitral-1.jpg"],
    base_price: 180000,
    material_cost: 55000,
    production_days: 10,
    profit_margin: 69,
    is_visible: true,
    is_featured: true,
    dimensions: "Ø45cm x 35cm alto",
    materials: "Vidrio Tiffany, fierro negro, cable textil",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Parrilla Custom Artesanal",
    slug: "parrilla-custom-artesanal",
    sku: "OUT-001",
    category_id: "outdoor",
    short_description: "Parrilla de fierro fundido con diseño personalizado y patas regulables",
    long_description: "Parrilla de alto rendimiento con fierro de 6mm de espesor, parrillas de acero inoxidable y diseño personalizable. Incluye cajón de cenizas, regulador de altura y acabado antioxidante.",
    techniques: ["soldadura", "construccion"],
    images: ["/images/parrilla-1.jpg"],
    base_price: 320000,
    material_cost: 95000,
    production_days: 7,
    profit_margin: 70,
    is_visible: true,
    is_featured: false,
    dimensions: "120cm x 60cm x 85cm",
    materials: "Fierro 6mm, acero inoxidable AISI 304",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Set Tablas de Cocina en Resina",
    slug: "set-tablas-cocina-resina",
    sku: "DEC-001",
    category_id: "decoracion",
    short_description: "Set de 3 tablas para cortar en madera y resina epóxica con incrustaciones",
    long_description: "Set de tablas de cortar artísticas que son también piezas decorativas. Madera de olivo con resina epóxica transparente e incrustaciones de minerales del norte de Chile.",
    techniques: ["carpinteria", "resina"],
    images: ["/images/tablas-resina-1.jpg"],
    base_price: 85000,
    material_cost: 22000,
    production_days: 5,
    profit_margin: 74,
    is_visible: true,
    is_featured: false,
    dimensions: "Grande: 35x25cm, Mediana: 28x18cm, Pequeña: 20x13cm",
    materials: "Madera olivo, resina epóxica, minerales",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
